# Use the official Python image
FROM python:3.10-slim-buster

# Set the working directory
WORKDIR /bot

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the bot's source code
COPY . .

# Specify the command to run the bot
CMD ["python", "main.py"]
